version: '3.7'
volumes:
  wp_data: 

  
services:
  db:
    image: mysql:5.7
    container_name: wordpress-db
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: rootPassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
      - 8889:3306
    networks:
            wp-back:
                ipv4_address: 172.28.1.1
      
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-site
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress_files:/var/www/html
    networks:
            wp-back:
                ipv4_address: 172.28.1.3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress_files:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    environment:
       VIRTUAL_HOST: dev.prowebx.fr
       LETSENCRYPT_HOST: dev.prowebx.fr
       LETSENCRYPT_EMAIL: EMAIL
       SSL_POLICY: Mozilla-Modern
       LETSENCRYPT_TEST: 'true'
    networks:
            wp-back:
                ipv4_address: 172.28.1.2
    restart: always


networks:
   wp-back:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
