version: '3.7'
volumes:
  wp_data: 

services:
  db:
    image: mysql:5.7
    container_name: wordpress-db
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: rootPassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
      - 8889:3306
      
  
